
  let parrafo = "<b>Atrévete a jugar y explorar nuevas conexiones</b>. Este juego te reta a completar desafíos de distintos niveles de dificultad, desde los más simples hasta los más desafiantes. ¿Estás listo para elegir tu destino?<br><br>";

  let parrafo2="<b>Importante:</b> Durante el juego, se revelarán y realizarán cosas que probablemente no sabías de tu pareja o amigos. Por eso, pedimos manejar todo con discreción para garantizar una experiencia más divertida y cómoda para todos.<br><br><ul><li> Si juegas con tu pareja, esperamos que este juego fortalezca su relación y les permita descubrir y disfrutar cosas nuevas juntos</li>.<br><li> Si juegas con amigos no se acepta que tu amistad sea una excusa para cumplir con los retos, asi que olvida que son amigos y la diversión estará garantizada, ¡incluso puede ser aún más emocionante!</li><br></ul>Recomendamos cumplir con la mayor cantidad de retos posibles y sumergirse por completo en la experiencia para disfrutar al máximo.🎉 <br>"

  let niveles="<ul><li><b><FONT COLOR='#73ddf5'>Cielo</FONT></b>: Empezaremos con retos fáciles para romper el hielo.</li><li><br> <b><FONT COLOR='#58e088'>Tierra</FONT></b>: Desafíos más complejos que pondrán a prueba tu sinceridad.</li><li><br> <b><FONT COLOR='#ea532f'>Infierno</FONT></b>: Pruebas difíciles para los más valientes y atrevidos.<br><br></li></ul>"
  let reglas="<b>Reglas del Juego</b><br><br><b> Regla #1:</b> Consigue un licor o bebida embriagante para el juego.<br><br> <b>Regla #2:</b> Comenzaremos calentando el ambiente. Cada integrante del grupo deberá tomar tres copas de lo que estén bebiendo para preparar el terreno.<br><br> <b>Regla #3:</b> Si un jugador decide no cumplir un reto, deberá tomar una copa de la bebida en cuestión. Algunas cartas tienen reglas especiales que te obligan a tomar doble copa. Si te toca una de estas, ¡no hay escapatoria!<br><br> <b>Regla #4:</b>Para elegir las cartas existe una secuencia obligatoria solo los primeros 3 turnos se escoje la carta que quieras, después: <br><br><ul><li>No puedes escoger el mismo tipo de carta más de dos veces seguidas.</li> <br><li>Por ejemplo, si eliges cielo dos veces, la siguiente carta deberá ser infierno, lo mismo con tierra.</li></ul><br> <b>Regla #5:</b> La más importante: <b>'LO QUE PASE EN LA PROFECIA, SE QUEDA EN LA PROFECIA.'</b> Lo que suceda durante el juego es confidencial y debe quedar entre los jugadores.<br><br>"

  let parraro3="Hay algunas cartas que están repetidas, pero es con el objetivo de que los otros jugadores también hagan retos que ya hiciste, entonces, si te sale carta repetida, tienes que tomar una copa del licor en cuestión y entregarle la carta al que quieras y este estará obligado a hacerla.<br><br><b>Sigue las reglas</b>, sumérgete en la experiencia y descubre secretos, habilidades y curiosidades de tus amigos o pareja. ¡Prometemos risas, sorpresas y momentos únicos que fortalecerán sus lazos como nunca antes!<br><br>Este programa fue creado por la comunidad de programadores de Medellín, inspirado en el juego del famoso youtuber Lebriah. Cabe aclarar que el juego no es exactamente igual y no tiene los mismos retos y dinámicas."

export {parrafo, parrafo2, parraro3, reglas, niveles}